/*
 * Account Information APIs
 * Swagger specification for Account Information APIs
 *
 * OpenAPI spec version: v1.0.0
 * Contact: Craig.Greenhouse@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.jeelis.psd2hub.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.jeelis.psd2hub.client.model.AccountTransactionsGETResponseAmount;
import com.jeelis.psd2hub.client.model.AccountTransactionsGETResponseBalance;
import com.jeelis.psd2hub.client.model.AccountTransactionsGETResponseBankTransactionCode;
import com.jeelis.psd2hub.client.model.AccountTransactionsGETResponseMerchantDetails;
import com.jeelis.psd2hub.client.model.AccountTransactionsGETResponseProprietaryBankTransactionCode;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * AccountTransactionsGETResponseData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-30T02:03:16.815+02:00")
public class AccountTransactionsGETResponseData {
  @SerializedName("AccountId")
  private String accountId = null;

  @SerializedName("TransactionId")
  private String transactionId = null;

  @SerializedName("TransactionReference")
  private String transactionReference = null;

  @SerializedName("Amount")
  private AccountTransactionsGETResponseAmount amount = null;

  /**
   * Indicates whether the transaction is a credit or a debit entry.
   */
  @JsonAdapter(CreditDebitIndicatorEnum.Adapter.class)
  public enum CreditDebitIndicatorEnum {
    CREDIT("Credit"),
    
    DEBIT("Debit");

    private String value;

    CreditDebitIndicatorEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CreditDebitIndicatorEnum fromValue(String text) {
      for (CreditDebitIndicatorEnum b : CreditDebitIndicatorEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<CreditDebitIndicatorEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CreditDebitIndicatorEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CreditDebitIndicatorEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return CreditDebitIndicatorEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("CreditDebitIndicator")
  private CreditDebitIndicatorEnum creditDebitIndicator = null;

  /**
   * Status of a transaction entry on the books of the account servicer.
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    BOOKED("Booked"),
    
    PENDING("Pending");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("Status")
  private StatusEnum status = null;

  @SerializedName("BookingDateTime")
  private DateTime bookingDateTime = null;

  @SerializedName("ValueDateTime")
  private DateTime valueDateTime = null;

  @SerializedName("TransactionInformation")
  private String transactionInformation = null;

  @SerializedName("AddressLine")
  private String addressLine = null;

  @SerializedName("BankTransactionCode")
  private AccountTransactionsGETResponseBankTransactionCode bankTransactionCode = null;

  @SerializedName("ProprietaryBankTransactionCode")
  private AccountTransactionsGETResponseProprietaryBankTransactionCode proprietaryBankTransactionCode = null;

  @SerializedName("Balance")
  private AccountTransactionsGETResponseBalance balance = null;

  @SerializedName("MerchantDetails")
  private AccountTransactionsGETResponseMerchantDetails merchantDetails = null;

  public AccountTransactionsGETResponseData accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.
   * @return accountId
  **/
  @ApiModelProperty(required = true, value = "A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public AccountTransactionsGETResponseData transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Unique identifier for the transaction within an servicing institution. This identifier is both unique and immutable.
   * @return transactionId
  **/
  @ApiModelProperty(value = "Unique identifier for the transaction within an servicing institution. This identifier is both unique and immutable.")
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public AccountTransactionsGETResponseData transactionReference(String transactionReference) {
    this.transactionReference = transactionReference;
    return this;
  }

   /**
   * Unique reference for the transaction. This reference is optionally populated, and may as an example be the FPID in the Faster Payments context.
   * @return transactionReference
  **/
  @ApiModelProperty(value = "Unique reference for the transaction. This reference is optionally populated, and may as an example be the FPID in the Faster Payments context.")
  public String getTransactionReference() {
    return transactionReference;
  }

  public void setTransactionReference(String transactionReference) {
    this.transactionReference = transactionReference;
  }

  public AccountTransactionsGETResponseData amount(AccountTransactionsGETResponseAmount amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public AccountTransactionsGETResponseAmount getAmount() {
    return amount;
  }

  public void setAmount(AccountTransactionsGETResponseAmount amount) {
    this.amount = amount;
  }

  public AccountTransactionsGETResponseData creditDebitIndicator(CreditDebitIndicatorEnum creditDebitIndicator) {
    this.creditDebitIndicator = creditDebitIndicator;
    return this;
  }

   /**
   * Indicates whether the transaction is a credit or a debit entry.
   * @return creditDebitIndicator
  **/
  @ApiModelProperty(required = true, value = "Indicates whether the transaction is a credit or a debit entry.")
  public CreditDebitIndicatorEnum getCreditDebitIndicator() {
    return creditDebitIndicator;
  }

  public void setCreditDebitIndicator(CreditDebitIndicatorEnum creditDebitIndicator) {
    this.creditDebitIndicator = creditDebitIndicator;
  }

  public AccountTransactionsGETResponseData status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Status of a transaction entry on the books of the account servicer.
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Status of a transaction entry on the books of the account servicer.")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public AccountTransactionsGETResponseData bookingDateTime(DateTime bookingDateTime) {
    this.bookingDateTime = bookingDateTime;
    return this;
  }

   /**
   * Date and time when a transaction entry is posted to an account on the account servicer&#39;s books. Usage: Booking date is the expected booking date, unless the status is booked, in which case it is the actual booking date.
   * @return bookingDateTime
  **/
  @ApiModelProperty(required = true, value = "Date and time when a transaction entry is posted to an account on the account servicer's books. Usage: Booking date is the expected booking date, unless the status is booked, in which case it is the actual booking date.")
  public DateTime getBookingDateTime() {
    return bookingDateTime;
  }

  public void setBookingDateTime(DateTime bookingDateTime) {
    this.bookingDateTime = bookingDateTime;
  }

  public AccountTransactionsGETResponseData valueDateTime(DateTime valueDateTime) {
    this.valueDateTime = valueDateTime;
    return this;
  }

   /**
   * Date and time at which assets become available to the account owner in case of a credit entry, or cease to be available to the account owner in case of a debit entry.  Usage: If entry status is pending and value date is present, then the value date refers to an expected/requested value date. For entries subject to availability/float and for which availability information is provided, the value date must not be used. In this case the availability component identifies the  number of availability days.
   * @return valueDateTime
  **/
  @ApiModelProperty(value = "Date and time at which assets become available to the account owner in case of a credit entry, or cease to be available to the account owner in case of a debit entry.  Usage: If entry status is pending and value date is present, then the value date refers to an expected/requested value date. For entries subject to availability/float and for which availability information is provided, the value date must not be used. In this case the availability component identifies the  number of availability days.")
  public DateTime getValueDateTime() {
    return valueDateTime;
  }

  public void setValueDateTime(DateTime valueDateTime) {
    this.valueDateTime = valueDateTime;
  }

  public AccountTransactionsGETResponseData transactionInformation(String transactionInformation) {
    this.transactionInformation = transactionInformation;
    return this;
  }

   /**
   * Further details of the transaction. This is the transaction narrative, which is unstructured text.
   * @return transactionInformation
  **/
  @ApiModelProperty(value = "Further details of the transaction. This is the transaction narrative, which is unstructured text.")
  public String getTransactionInformation() {
    return transactionInformation;
  }

  public void setTransactionInformation(String transactionInformation) {
    this.transactionInformation = transactionInformation;
  }

  public AccountTransactionsGETResponseData addressLine(String addressLine) {
    this.addressLine = addressLine;
    return this;
  }

   /**
   * Information that locates and identifies a specific address, as defined by postal services, that is presented in free format text.
   * @return addressLine
  **/
  @ApiModelProperty(value = "Information that locates and identifies a specific address, as defined by postal services, that is presented in free format text.")
  public String getAddressLine() {
    return addressLine;
  }

  public void setAddressLine(String addressLine) {
    this.addressLine = addressLine;
  }

  public AccountTransactionsGETResponseData bankTransactionCode(AccountTransactionsGETResponseBankTransactionCode bankTransactionCode) {
    this.bankTransactionCode = bankTransactionCode;
    return this;
  }

   /**
   * Get bankTransactionCode
   * @return bankTransactionCode
  **/
  @ApiModelProperty(value = "")
  public AccountTransactionsGETResponseBankTransactionCode getBankTransactionCode() {
    return bankTransactionCode;
  }

  public void setBankTransactionCode(AccountTransactionsGETResponseBankTransactionCode bankTransactionCode) {
    this.bankTransactionCode = bankTransactionCode;
  }

  public AccountTransactionsGETResponseData proprietaryBankTransactionCode(AccountTransactionsGETResponseProprietaryBankTransactionCode proprietaryBankTransactionCode) {
    this.proprietaryBankTransactionCode = proprietaryBankTransactionCode;
    return this;
  }

   /**
   * Get proprietaryBankTransactionCode
   * @return proprietaryBankTransactionCode
  **/
  @ApiModelProperty(value = "")
  public AccountTransactionsGETResponseProprietaryBankTransactionCode getProprietaryBankTransactionCode() {
    return proprietaryBankTransactionCode;
  }

  public void setProprietaryBankTransactionCode(AccountTransactionsGETResponseProprietaryBankTransactionCode proprietaryBankTransactionCode) {
    this.proprietaryBankTransactionCode = proprietaryBankTransactionCode;
  }

  public AccountTransactionsGETResponseData balance(AccountTransactionsGETResponseBalance balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Get balance
   * @return balance
  **/
  @ApiModelProperty(value = "")
  public AccountTransactionsGETResponseBalance getBalance() {
    return balance;
  }

  public void setBalance(AccountTransactionsGETResponseBalance balance) {
    this.balance = balance;
  }

  public AccountTransactionsGETResponseData merchantDetails(AccountTransactionsGETResponseMerchantDetails merchantDetails) {
    this.merchantDetails = merchantDetails;
    return this;
  }

   /**
   * Get merchantDetails
   * @return merchantDetails
  **/
  @ApiModelProperty(value = "")
  public AccountTransactionsGETResponseMerchantDetails getMerchantDetails() {
    return merchantDetails;
  }

  public void setMerchantDetails(AccountTransactionsGETResponseMerchantDetails merchantDetails) {
    this.merchantDetails = merchantDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountTransactionsGETResponseData accountTransactionsGETResponseData = (AccountTransactionsGETResponseData) o;
    return Objects.equals(this.accountId, accountTransactionsGETResponseData.accountId) &&
        Objects.equals(this.transactionId, accountTransactionsGETResponseData.transactionId) &&
        Objects.equals(this.transactionReference, accountTransactionsGETResponseData.transactionReference) &&
        Objects.equals(this.amount, accountTransactionsGETResponseData.amount) &&
        Objects.equals(this.creditDebitIndicator, accountTransactionsGETResponseData.creditDebitIndicator) &&
        Objects.equals(this.status, accountTransactionsGETResponseData.status) &&
        Objects.equals(this.bookingDateTime, accountTransactionsGETResponseData.bookingDateTime) &&
        Objects.equals(this.valueDateTime, accountTransactionsGETResponseData.valueDateTime) &&
        Objects.equals(this.transactionInformation, accountTransactionsGETResponseData.transactionInformation) &&
        Objects.equals(this.addressLine, accountTransactionsGETResponseData.addressLine) &&
        Objects.equals(this.bankTransactionCode, accountTransactionsGETResponseData.bankTransactionCode) &&
        Objects.equals(this.proprietaryBankTransactionCode, accountTransactionsGETResponseData.proprietaryBankTransactionCode) &&
        Objects.equals(this.balance, accountTransactionsGETResponseData.balance) &&
        Objects.equals(this.merchantDetails, accountTransactionsGETResponseData.merchantDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, transactionId, transactionReference, amount, creditDebitIndicator, status, bookingDateTime, valueDateTime, transactionInformation, addressLine, bankTransactionCode, proprietaryBankTransactionCode, balance, merchantDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountTransactionsGETResponseData {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    transactionReference: ").append(toIndentedString(transactionReference)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    creditDebitIndicator: ").append(toIndentedString(creditDebitIndicator)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    bookingDateTime: ").append(toIndentedString(bookingDateTime)).append("\n");
    sb.append("    valueDateTime: ").append(toIndentedString(valueDateTime)).append("\n");
    sb.append("    transactionInformation: ").append(toIndentedString(transactionInformation)).append("\n");
    sb.append("    addressLine: ").append(toIndentedString(addressLine)).append("\n");
    sb.append("    bankTransactionCode: ").append(toIndentedString(bankTransactionCode)).append("\n");
    sb.append("    proprietaryBankTransactionCode: ").append(toIndentedString(proprietaryBankTransactionCode)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    merchantDetails: ").append(toIndentedString(merchantDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

